from typing import List, Optional, Protocol

from app.domain.models.contest import ContestDiscoveryHit, ContestRun, ContestSource, ContestSubscription, TenantContestSource


class ContestRepository(Protocol):
    async def list_sources(self, enabled_only: bool = False) -> List[ContestSource]: ...
    async def get_source(self, source_id: str) -> Optional[ContestSource]: ...
    async def get_source_by_key(self, key: str) -> Optional[ContestSource]: ...
    async def save_source(self, source: ContestSource) -> None: ...
    async def delete_source(self, source_id: str) -> bool: ...

    async def list_subscriptions(self, tenant_id: str) -> List[ContestSubscription]: ...
    async def list_enabled_subscriptions(self) -> List[ContestSubscription]: ...
    async def get_subscription(self, tenant_id: str, subscription_id: str) -> Optional[ContestSubscription]: ...
    async def get_subscription_by_keyword(self, tenant_id: str, keyword: str) -> Optional[ContestSubscription]: ...
    async def save_subscription(self, subscription: ContestSubscription) -> None: ...
    async def delete_subscription(self, tenant_id: str, subscription_id: str) -> bool: ...

    async def has_discovery_hit(self, tenant_id: str, policy_id: str) -> bool: ...
    async def save_discovery_hit(self, hit: ContestDiscoveryHit) -> None: ...

    async def list_tenant_sources(self, tenant_id: str, enabled_only: bool = False) -> List[TenantContestSource]: ...
    async def list_enabled_tenant_sources(self) -> List[TenantContestSource]: ...
    async def get_tenant_source(self, tenant_id: str, source_id: str) -> Optional[TenantContestSource]: ...
    async def save_tenant_source(self, source: TenantContestSource) -> None: ...
    async def delete_tenant_source(self, tenant_id: str, source_id: str) -> bool: ...
    async def link_tenant_source_policy(self, tenant_id: str, source_id: str, policy_id: str) -> None: ...
    async def tenant_can_view_policy(self, tenant_id: str, policy_id: str) -> bool: ...

    async def save_run(self, run: ContestRun) -> None: ...
    async def list_runs(self, tenant_id: str, kind: str, target_id: str, limit: int = 10) -> List[ContestRun]: ...
