from typing import List, Optional, Protocol

from app.domain.models.contest import ContestDiscoveryHit, ContestSource, ContestSubscription


class ContestRepository(Protocol):
    async def list_sources(self, enabled_only: bool = False) -> List[ContestSource]: ...
    async def get_source(self, source_id: str) -> Optional[ContestSource]: ...
    async def get_source_by_key(self, key: str) -> Optional[ContestSource]: ...
    async def save_source(self, source: ContestSource) -> None: ...
    async def delete_source(self, source_id: str) -> bool: ...

    async def list_subscriptions(self, tenant_id: str) -> List[ContestSubscription]: ...
    async def list_enabled_subscriptions(self) -> List[ContestSubscription]: ...
    async def get_subscription(self, tenant_id: str, subscription_id: str) -> Optional[ContestSubscription]: ...
    async def get_subscription_by_keyword(self, tenant_id: str, keyword: str) -> Optional[ContestSubscription]: ...
    async def save_subscription(self, subscription: ContestSubscription) -> None: ...
    async def delete_subscription(self, tenant_id: str, subscription_id: str) -> bool: ...

    async def has_discovery_hit(self, tenant_id: str, policy_id: str) -> bool: ...
    async def save_discovery_hit(self, hit: ContestDiscoveryHit) -> None: ...
